{% set name = "otter-report" %}
{% set version = "0.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/otter-report-{{ version }}.tar.gz
  sha256: c040df0d2aadae7ac2260ce0b2543fdbcb8ad0febbb7de1b193406867bb48ba2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.3
    - setuptools-scm
  run:
    - configparser
    - jinja2
    - markdown
    - matplotlib-base
    - python >=3.3
    - pyyaml
    - tabulate

test:
  imports:
    - otter
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/transientlunatic/otter
  dev_url: https://github.com/transientlunatic/otter
  summary: The simple HTML report generator for Python jobs.
  license: MIT
  license_file: LICENSE
  description: |
    Otter is a simple HTML report generator for Python jobs.
    Otter was designed to produce reports on long-running jobs on
    remote machines, and send them to a web server, but it’s able to
    process many different outputs from Python scripts, and convert
    them into neat and readible HTML pages.

extra:
  recipe-maintainers:
    - duncanmmacleod
    - transientlunatic
